#!/bin/bash
#BSUB -J test_1295eb4c-0366-4175-9c69-8e36bcb04c55
#BSUB -q normal
#BSUB -n 1 
#BSUB -M 100
#BSUB -R "select[mem>100] rusage[mem=100]"
#BSUB -W 12:00
#BSUB -o .solosis/lsf/test_1295eb4c-0366-4175-9c69-8e36bcb04c55.log
set -euo pipefail
echo "hello world" > test.txt
status=$?
if [ $status -eq 0 ]; then
  echo " command was successful: Exit status: $status" | mail -s "Job status: test_1295eb4c-0366-4175-9c69-8e36bcb04c55" vm11@sanger.ac.uk
else
  echo " command failed: Exit status: $status" | mail -s "Job status: test_1295eb4c-0366-4175-9c69-8e36bcb04c55" vm11@sanger.ac.uk
fi
