#!/bin/bash
#BSUB -J test_ce947446-467d-4410-ad37-27777050d967
#BSUB -q normal
#BSUB -n 4 
#BSUB -M 50000
#BSUB -R "select[mem>50000] rusage[mem=50000]"
#BSUB -W 12:00
#BSUB -o .solosis/lsf/test_ce947446-467d-4410-ad37-27777050d967.log
set -euo pipefail
echo hello world
status=$?
if [ $status -eq 0 ]; then
  echo " command was successful: Exit status: $status" | mail -s "Job status: test_ce947446-467d-4410-ad37-27777050d967" vm11@sanger.ac.uk
else
  echo " command failed: Exit status: $status" | mail -s "Job status: test_ce947446-467d-4410-ad37-27777050d967" vm11@sanger.ac.uk
fi
