#!/bin/bash
#BSUB -J test_38e753d2-4f77-4840-9ab7-6da5fdd91c0e
#BSUB -q normal
#BSUB -n 4 
#BSUB -M 50000
#BSUB -R "select[mem>50000] rusage[mem=50000]"
#BSUB -W 12:00
#BSUB -o .solosis/lsf/test_38e753d2-4f77-4840-9ab7-6da5fdd91c0e.log
set -euo pipefail
echo "hello world" > test.txt
status=$?
if [ $status -eq 0 ]; then
  echo " command was successful: Exit status: $status" | mail -s "Job status: test_38e753d2-4f77-4840-9ab7-6da5fdd91c0e" vm11@sanger.ac.uk
else
  echo " command failed: Exit status: $status" | mail -s "Job status: test_38e753d2-4f77-4840-9ab7-6da5fdd91c0e" vm11@sanger.ac.uk
fi
