name: build-docs

on:
  push:
    branches: [dev]

  pull_request:
    branches: [main, dev]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./envs/requirements.txt          
          pip install -r ./envs/dev/requirements.txt
          pip install -r ./envs/build_config/requirements.txt
      - name: Sphinx Build
        working-directory: ./sphinx
        run: |
          make html
          touch _build/html/.nojekyll
