name: python-tests

on:
  push:
    branches: [main, dev]

  pull_request:
    branches: [main, dev]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./envs/requirements.txt
      - name: Run tests
        run: python -m pytest --cov --cov-report=xml tests/test_cli.py
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}